// <copyright file="PacketFunctions.h" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

//------------------------------------------------------------------------------
// <auto-generated>
//     This source code was auto-generated by an XSL transformation.
//     Do not change this file. Instead, change the XML data which contains
//     the packet definitions and re-run the transformation (publish/rebuild the
//     managed library project).
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#include "stdafx.h"

#include <coreclr_delegates.h>

#include "Network/Server/BankProtocol.h"
#include "PacketFunctions_CommonEnums.h"

/// <summary>
/// Extension methods to start writing messages of this namespace on a <see cref="Connection"/>.
/// </summary>
class PacketFunctions_Base
{
private:
    int32_t _handle = -1;

public:
    void SetHandle(const int32_t handle)
    {
        _handle = handle;
    }
    int32_t GetHandle() const
    {
        return _handle;
    }
};

#pragma pack(push, 1)
struct AreaSkillHitTarget
{
    uint16_t TargetId;
    BYTE AnimationCounter;
};
#pragma pack(pop)

/// <summary>
/// Extension methods to start writing messages of this namespace on a <see cref="Connection"/>.
/// </summary>
class PacketFunctions_ClientToServer_Custom : public PacketFunctions_Base
{
public:
    /// <summary>
    /// Sends a LoginLongPassword to this connection.
    /// </summary>
    /// <param name="username">The user name, "encrypted" with Xor3.</param>
    /// <param name="password">The password, "encrypted" with Xor3.</param>
    /// <param name="clientVersion">The client version.</param>
    /// <param name="clientSerial">The client serial.</param>
    /// <remarks>
    /// Is sent by the client when: The player tries to log into the game.
    /// Causes reaction on server side: The server is authenticating the sent login name and password. If it's correct,
    /// the state of the player is proceeding to be logged in.
    /// </remarks>
    void SendLogin(const wchar_t* username, const wchar_t* password, const BYTE* clientVersion,
                   const BYTE* clientSerial);

    /// <summary>
    /// Sends a stat point increase request for several points at once to this connection.
    /// </summary>
    /// <param name="statType">The stat to increase.</param>
    /// <param name="amount">The number of points to add to that stat.</param>
    /// <remarks>
    /// Not part of the original protocol (0xF3, 0xE0): the original client sends one packet per point, which makes
    /// spending a big pool of level-up-points slow. The server caps the amount at the available points.
    /// </remarks>
    void SendIncreaseCharacterStatPointMultiple(CharacterStatAttribute statType, uint16_t amount);

    /// <summary>
    /// Sends a master skill point add request for several points at once to this connection.
    /// </summary>
    /// <param name="skillId">The master skill to raise.</param>
    /// <param name="amount">The number of points to add to that skill.</param>
    /// <remarks>
    /// Not part of the original protocol (0xF3, 0xE1): the original client sends one packet per point, which makes
    /// filling a master skill tree slow. The server adds points until the amount is reached, the skill is at its
    /// maximum level, or the character runs out of master level up points.
    /// </remarks>
    void SendAddMasterSkillPointMultiple(uint16_t skillId, BYTE amount);

    /// <summary>
    /// Sends the answer of the reset confirmation dialog to this connection.
    /// </summary>
    /// <param name="resetTypeIndex">The reset type index of the corresponding confirmation request.</param>
    /// <param name="accepted">Whether the player accepted the reset.</param>
    /// <remarks>
    /// Not part of the original protocol (0xF3, 0xE2): the server announces a reset with a 0xF3, 0xE0 message
    /// and only performs it after this answer arrived.
    /// </remarks>
    void SendResetConfirmation(BYTE resetTypeIndex, bool accepted);

    /// <summary>
    /// Sends the request to move value between the character and the bank of its account.
    /// </summary>
    /// <param name="deposit">True to move the value into the bank, false to take it out.</param>
    /// <param name="currency">The currency to move.</param>
    /// <param name="amount">The amount to move; always positive.</param>
    /// <remarks>Not part of the original protocol (0xFB, 0x01).</remarks>
    void SendBankMoveValue(bool deposit, Net::Bank::Currency currency, int64_t amount);

    /// <summary>
    /// Sends the request to offer an item of the bank on the market.
    /// </summary>
    /// <param name="bankSlot">The box of the item in the item storage of the bank.</param>
    /// <param name="priceCurrency">The currency the seller wants to be paid in.</param>
    /// <param name="price">The price.</param>
    /// <remarks>Not part of the original protocol (0xFB, 0x04).</remarks>
    void SendMarketRegisterItem(BYTE bankSlot, Net::Bank::Currency priceCurrency, int64_t price);

    /// <summary>
    /// Sends the request to offer an amount of a currency of the bank on the market.
    /// </summary>
    /// <param name="offeredCurrency">The offered currency.</param>
    /// <param name="offeredAmount">The offered amount.</param>
    /// <param name="priceCurrency">The currency the seller wants to be paid in.</param>
    /// <param name="price">The price.</param>
    /// <remarks>Not part of the original protocol (0xFB, 0x05).</remarks>
    void SendMarketRegisterCurrency(Net::Bank::Currency offeredCurrency, int64_t offeredAmount,
                                    Net::Bank::Currency priceCurrency, int64_t price);

    /// <summary>
    /// Sends the request to buy an offer of the market.
    /// </summary>
    /// <param name="listingId">The identifier of the offer, as it arrived.</param>
    /// <remarks>Not part of the original protocol (0xFB, 0x06).</remarks>
    void SendMarketBuy(const BYTE* listingId);

    /// <summary>
    /// Sends the request to take an own offer off the market.
    /// </summary>
    /// <param name="listingId">The identifier of the offer, as it arrived.</param>
    /// <remarks>Not part of the original protocol (0xFB, 0x07).</remarks>
    void SendMarketCancel(const BYTE* listingId);

    /// <summary>
    /// Sends the request to list the offers of the market.
    /// </summary>
    /// <param name="page">The page to show, starting at 0.</param>
    /// <param name="priceCurrencyFilter">The currency the price has to be in; Net::Bank::AnyCurrency for any.</param>
    /// <param name="ownOffersOnly">True to list only the offers of this account.</param>
    /// <param name="nameFilter">A text which the name of the offer has to contain.</param>
    /// <remarks>Not part of the original protocol (0xFB, 0x08).</remarks>
    void SendMarketList(BYTE page, BYTE priceCurrencyFilter, bool ownOffersOnly, const wchar_t* nameFilter);

    /// <summary>
    /// Tells the server that the bank dialog was opened or closed.
    /// </summary>
    /// <param name="open">True when the dialog was opened, false when it was closed.</param>
    /// <remarks>
    /// Not part of the original protocol (0xFB, 0x0A). The bank is reached from a button of the
    /// inventory, so opening it is a request of its own rather than the answer to a talk.
    /// </remarks>
    void SendBankDialog(bool open);

    /// <summary>
    /// Sends the request to show a page of the ledger of the bank.
    /// </summary>
    /// <param name="page">The page to show, starting at 0.</param>
    /// <remarks>Not part of the original protocol (0xFB, 0x09).</remarks>
    void SendBankLedger(BYTE page);
};

/// <summary>
/// Extension methods to start writing messages of this namespace on a <see cref="Connection"/>.
/// </summary>
class PacketFunctions_ConnectServer_Custom : public PacketFunctions_Base
{
};

/// <summary>
/// Extension methods to start writing messages of this namespace on a <see cref="Connection"/>.
/// </summary>
class PacketFunctions_ChatServer_Custom : public PacketFunctions_Base
{
public:
    /// <summary>
    /// Sends a Authenticate to this connection.
    /// </summary>
    /// <param name="roomId">The room id.</param>
    /// <param name="token">The token to authenticate the client.</param>
    /// <remarks>
    /// Is sent by the client when: This packet is sent by the client after it connected to the server, to authenticate
    /// itself. Causes reaction on server side: The server will check the token. If it's correct, the client gets added
    /// to the requested chat room.
    /// </remarks>
    void SendAuthenticateExt(uint16_t roomId, uint32_t token);

    /// <summary>
    /// Sends a ChatMessage to this connection.
    /// </summary>
    /// <param name="senderIndex">The sender index.</param>
    /// <param name="message">The message.</param>
    /// <remarks>
    /// Is sent by the server when: This packet is sent by the server after another chat client sent a message to the
    /// current chat room. Causes reaction on client side: The client will show the message.
    /// </remarks>
    void SendChatMessageExt(BYTE senderIndex, const wchar_t* message);
};